language: ruby
script: true
before_deploy:
  - gem install --no-rdoc --no-ri fpm
  - gem which fpm
  - echo $PATH
  - which -a fpm
deploy:
  provider: script
  script: fpm --version
skip_cleanup: true
on:
  all_branches: true
