language: ruby
dist: precise
script: true
before_deploy:
  - gem install --no-rdoc --no-ri fpm
  - gem which fpm
  - echo $PATH
  - rvm list rubies
  - which -a fpm
deploy:
  provider: script
  script: bash -c '/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/fpm --version'
skip_cleanup: true
on:
  all_branches: true
